### ISSUE TITLE
Error-k must be between 1 and min(A.shape). What is k?

### ISSUE THREAD

**Issue by Jigyasa3** [cjm007/DEICODE#49]
$deicode --in-biom transposed_hemicellulose_bacterial_phyla.csv.txt_json.biom --output-dir decodier_transposed_hemicellulose_bacterial_phyla.csv.txt_json.biom --min-sample-count 10 --min-feature-count 1 --max_iterations 1 --n_components 2

#Some information about my data-
#my max. no. of samples are 141. 
#maximum feature count is 2.

error- 
Traceback (most recent call last):
  File "/home/j/jigyasa-arora/.local/bin/deicode", line 10, in <module>
    sys.exit(standalone_rpca())
  File "/apps/free72/python/3.7.3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/apps/free72/python/3.7.3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/apps/free72/python/3.7.3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/apps/free72/python/3.7.3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/j/jigyasa-arora/.local/lib/python3.7/site-packages/deicode/scripts/_standalone_rpca.py", line 45, in standalone_rpca
    max_iterations)
  File "/home/j/jigyasa-arora/.local/lib/python3.7/site-packages/deicode/rpca.py", line 39, in rpca
    max_iterations=max_iterations).fit(rclr(table))
  File "/home/j/jigyasa-arora/.local/lib/python3.7/site-packages/deicode/matrix_completion.py", line 99, in fit
    self._fit()
  File "/home/j/jigyasa-arora/.local/lib/python3.7/site-packages/deicode/matrix_completion.py", line 117, in _fit
    tol=self.tol).solve(X_sparse)
  File "/home/j/jigyasa-arora/.local/lib/python3.7/site-packages/deicode/optspace.py", line 115, in solve
    U, S, V = svds(obs, self.n_components, which='LM')
  File "/apps/free72/python/3.7.3/lib/python3.7/site-packages/scipy-1.3.0-py3.7-linux-x86_64.egg/scipy/sparse/linalg/eigen/arpack/arpack.py", line 1786, in svds
    raise ValueError("k must be between 1 and min(A.shape), k=%d" % k)
ValueError: k must be between 1 and min(A.shape), k=2

What is k?
If the number of features are less, how do we account for that in the software?

**Comment by cameronmartino** [comment]
Hi @Jigyasa3, 

That error indicates that the minimum dimension of your data is less than or equal to the n_components parameter (it much be larger for dimensionally reduction to make sense). When you say:

> #my max. no. of samples are 141.
> #maximum feature count is 2.

Do you mean your data is of the shape 141 columns by 2 rows?

**Comment by cameronmartino** [comment]
Sounds like this was resolved in issue #50. Closing this issue - please reopen it if you have more questions.
